engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
    checks:
      Similar code:
        enabled: false
engines:
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
engines:
  eslint:
    enabled: true
    checks:
      no-multiple-empty-lines:
        enabled: false

