engines:
  duplication:
    enabled: false
    checks:
      Similar code:
        enabled: false
        config:
          languages:
          - javascript:
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
      no-multiple-empty-lines:
        enabled: false
exclude_paths:
- "templates/"
