engines:
  # ... CONFIG CONTENT ...
  duplication:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      Similar code:
        enabled: false
# ... CONFIG CONTENT ...
engines:
  # ... CONFIG CONTENT ...
  eslint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      import/extensions:
        enabled: false
# ... CONFIG CONTENT ...
engines:
  # ... CONFIG CONTENT ...
  eslint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      no-multiple-empty-lines:
        enabled: false
# ... CONFIG CONTENT ...

