engines:
  duplication:
    enabled: false
    checks:
      Similar code:
        enabled: false
        config:
          languages:
          - javascript:
    
engines:
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
engines:
  eslint:
    enabled: true
    checks:
      no-multiple-empty-lines:
        enabled: false

