export default {
  CREATE_NEW_USER: 'CREATE_NEW_USER',
  CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
  LOG_USER_OUT: 'LOG_USER_OUT',
  LOG_USER_OUT_FAILURE: 'LOG_USER_OUT_FAILURE',
  SET_CURRENT_USER: 'SET_CURRENT_USER'
};
